version: "3"
services:
  golang:
    build:
      context: "./golang"
      dockerfile: "Dockerfile"
    ports:
      - "9000:9000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - ./golang/.local/share/fish/fish_history:/root/.local/share/fish/fish_history
      - ..:/workspace
      - overwrite:/workspace/.devcontainer/postgres/data
      - overwrite:/workspace/.devcontainer/postgres/pgadmin
  postgres:
    build:
      context: "./postgres"
      dockerfile: "Dockerfile"
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: qiita
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4:4.24
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./postgres/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  overwrite:
    driver: 'local'